language: node_js
node_js:
  - node
script: >
    npm run travis-tests # &&
    # gzip -c built/webamp.bundle.min.js > built/webamp.bundle.min.js.gz &&
    # python node_modules/travis-weigh-in/weigh_in.py built/webamp.bundle.min.js &&
    # python node_modules/travis-weigh-in/weigh_in.py built/webamp.bundle.min.js.gz
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy: echo webamp.org > built/CNAME
deploy:
    local-dir: "./built/"
    verbose: true
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    on:
        branch: master