name: "Internet Archvie Integration Tests"

on:
  push:
  schedule:
    - cron: "0 8 * * *"

jobs:
  ia-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Run Tests
        run: |
          cd packages/archive-org-webamp-integration-tests
          yarn
          node ./index.js
        env:
          CI: true
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: error
          path: packages/webamp/experiments/archive-org-integration-tests/error.png
